services:
  enqueue_elastica.populate_processor:
      class: 'Enqueue\ElasticaBundle\Async\ElasticaPopulateProcessor'
      arguments:
          - '@fos_elastica.provider_registry'

  enqueue_elastica.purge_fos_elastic_populate_queue_listener:
      class: 'Enqueue\ElasticaBundle\Listener\PurgeFosElasticPopulateQueueListener'
      arguments:
          - '@enqueue.transport.context'
      tags:
          -  { name: 'kernel.event_subscriber' }
